name: Bug report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: "
在提交之前，请确认
Please verify that you've followed these steps
"
      options:
        - label: "
确保你使用的是**本仓库**最新的 AMEI 内核版本（基于 mihomo）
Ensure you are using the latest AMEI fork from **this repository**.
"
          required: true
        - label: "
如果你可以自己 debug 并解决的话，提交 PR 吧
Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
"
          required: false
        - label: "
我已经在 [Issue Tracker](……/) 中找过我要提出的问题
I have searched on the [issue tracker](……/) for a related issue.
"
          required: true
        - label: "
我已经使用 Alpha 分支版本测试过，问题依旧存在
I have tested using the dev branch, and the issue still exists.
"
          required: true
        - label: "
我已经仔细看过 [Documentation](docs/) 并无法自行解决问题
I have read the [documentation](docs/) and was unable to solve the issue.
"
          required: true
        - label: "
这是 AMEI 内核的问题，并非上游 Mihomo 或其他衍生版本的特定问题
This is an issue of the AMEI core, not upstream Mihomo or other derivatives.
"
          required: true
  - type: input
    attributes:
      label: AMEI version
      description: "use `mihomo -v`"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
        - OpenBSD/FreeBSD
  - type: textarea
    attributes:
      render: yaml
      label: "AMEI config"
      description: "
在下方附上 AMEI 内核配置文件，请确保配置文件中没有敏感信息（比如：服务器地址，密码，端口等）
Paste the AMEI core configuration file below, please make sure that there is no sensitive information in the configuration file (e.g., server address/url, password, port)
"
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: AMEI log
      description: "
在下方附上 AMEI 内核日志，log level 使用 DEBUG
Paste the AMEI core log below with the log level set to `DEBUG`.
"
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
